server:
  port: 80
spring:
  application:
    name: post
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    username: sa
    password:
    schema: classpath:schema.sql
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
    auto-mapping-unknown-column-behavior: none
  mapper-locations: mapper/*.xml

